import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/common/sidebar";
import styles from "../styles/Home.module.css";
import { useRecoilValue } from "recoil";
import { serviceState } from "../atoms/service";
import { fileShortSvcNameSelector } from "../atoms/file";
const Service: NextPage = () => {
  const services = useRecoilValue(serviceState);
  const shortSvcName = useRecoilValue(fileShortSvcNameSelector);
  return (
    <Sidebar linkItems={shortSvcName}>
      <div className={styles.container}>
        <Head>
          <title>grpc reflection</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        test
      </div>
    </Sidebar>
  );
};

export default Service;
