import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import { Button, Link } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import { GrpcServices, GrpcServiceName } from "./api/types";
const Home: NextPage = () => {
  const [services, setServices] = useState<GrpcServiceName[]>([]);
  const [files, setFiles] = useState<
    { [k: string]: any } & {
      name: string;
      service: Array<{ method: Array<{ name: string }> }>;
    }
  >();
  useEffect(() => {
    const fetchAll = async () => {
      const svcs = await fetch("/api/services");
      const svcBody = (await svcs.json()) as GrpcServices;
      setServices(svcBody.services);
      const sbls = await fetch("/api/symbol", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(svcBody),
      });
      const sblBody = await sbls.json();
      setFiles(sblBody.files);
    };
    fetchAll();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>grpc reflection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TableContainer>
          <Table variant="striped" colorScheme="telegram" size="lg">
            <TableCaption placement="top">
              All Implemented Services
            </TableCaption>
            <Thead>
              <Tr>
                <Th>Service</Th>
                <Th>FilePath</Th>
                <Th>Messages</Th>
              </Tr>
            </Thead>
            <Tbody>
              {services.map((s, i) => (
                <Tr key={s + i}>
                  <Td>
                    <NextLink href={`/${encodeURIComponent(s)}`} passHref>
                      <Link>{s}</Link>
                    </NextLink>
                  </Td>
                  <Td>{files && files[s].name}</Td>
                  <Td>
                    {files &&
                      files[s].messageType.map((m: { name: string }) => (
                        <p key={m.name}>{m.name}</p>
                      ))}
                  </Td>
                  <Td>
                    <Button colorScheme="teal" variant="outline">
                      Call
                    </Button>
                  </Td>
                </Tr>
              ))}
            </Tbody>
          </Table>
        </TableContainer>
        <>
          {/* {files.map((f, i) => (
            <div key={f + i}>{f}</div>
          ))} */}
        </>
      </main>
    </div>
  );
};

export default Home;
