import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import { Button, Link } from "@chakra-ui/react";
import { useEffect } from "react";
import {
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import { FileDescriptions, GrpcServices } from "./api/types";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import {  useRecoilState } from "recoil";
import { serviceState } from "../atoms/service";
import { fileState } from "../atoms/file";
const Home: NextPage = () => {
  const [services, setServices] = useRecoilState(serviceState)
  const [files, setFiles] = useRecoilState(fileState);
  useEffect(() => {
    const fetchAll = async () => {
      const svcs = await fetch("/api/services");
      const svcBody = (await svcs.json()) as GrpcServices;
      setServices(svcBody.services);
      const sbls = await fetch("/api/symbol", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(svcBody),
      });
      const sblBody = await sbls.json() as FileDescriptions;
      setFiles(sblBody.files);
    };
    fetchAll();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>grpc reflection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TableContainer>
          <Table variant="striped" colorScheme="telegram" size="lg">
            <TableCaption placement="top">
              All Implemented Services
            </TableCaption>
            <Thead>
              <Tr>
                <Th>Service</Th>
                <Th>FilePath</Th>
                <Th>Messages</Th>
              </Tr>
            </Thead>
            <Tbody>
              {services.map((s, i) => (
                <Tr key={s + i}>
                  <Td>
                    <NextLink href={`/${encodeURIComponent(s)}`} passHref>
                      <Link>{s}</Link>
                    </NextLink>
                  </Td>
                  <Td>{Object.keys(files).length!==0 && files[s]?.name}</Td>
                  <Td>
                    {Object.keys(files).length!==0 &&
                      files[s]?.messageType.map((m: { name: string }) => (
                        <p key={m.name}>{m.name}</p>
                      ))}
                  </Td>
                  <Td>
                  <NextLink href={`/${Object.keys(files).length!==0 && encodeURIComponent(files[s]?.name)}`} passHref>
                    <Button as="a" colorScheme="teal" variant="outline" rightIcon={<ArrowForwardIcon />}>
                      Call
                    </Button>
                    </NextLink>
                  </Td>
                </Tr>
              ))}
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </div>
  );
};


export default Home;
